# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    continue-on-error: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Compile with gradle
        run: ./gradlew assemble

  code-style:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Code Style with ktlint
        run: ./gradlew ktlintFormat

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      SECRET: dna8sdh8ashd8asnd8asd
      ISSUER: turnierverwaltung
      USER: root
      PASSWORD: secret
      DATABASE: authentication
      SERVER: localhost
    services:
      postgres:
        # Docker Hub image
        image: postgres:latest
        env:
          POSTGRES_USER: "root"
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: "authentication"
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup PostgreSQL Database
        run: createdb -h localhost -U root -W authentication
      - name: Test with gradle
        run: ./gradlew test
