# This is a basic workflow to help you get started with Actions

name: Code-Style

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  code-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Code Style with ktlint
        run: ./gradlew ktlintCheck
